-- Insertar Categorías
INSERT INTO CATEGORIA (nombre, descripcion, es_activa) VALUES
('Tortas y Pasteles', 'Deliciosas tortas y pasteles para todas las ocasiones', true),
('Bollería y Masas Dulces', 'Variedad de bollería fresca y masas dulces', true),
('Panes Especiales', 'Panes artesanales y panes especiales', true),
('Galletas y Pequeños Dulces', 'Galletas, brownies y pequeños dulces', true);

-- Insertar Productos - Tortas y Pasteles
INSERT INTO PRODUCTO (nombre, descripcion, precio, imagen_url, categoria, stock, es_activo) VALUES
('Torta de Tres Leches', 'Un bizcocho esponjoso bañado en una mezcla de tres tipos de leche (leche evaporada, crema de leche y leche condensada), usualmente cubierto con merengue o crema batida.', 22990, 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh2FNGpdb9xllndHQkGvVVvkSWs_xoyY4Jmz1gRGQJdi0E-2qAAx71oEUusuBDJHMHly4axFJCYFQcbUOul2U5yoqnkePJy6yEVvUjOvigHNoQ_k2qfgsMDkbwjEaqqxrogLetbKJRA0EkO/s0/torta-tres-leches-menos-azucar.jpg', 'Tortas y Pasteles', 10, true),
('Pastel de Chocolate (Torta de Chocolate)', 'Un clásico pastel hecho con chocolate o cacao en polvo, que puede tener múltiples capas, relleno y cobertura de ganache, buttercream o fudge de chocolate.', 24990, 'https://amoradulce.com/wp-content/uploads/2019/12/Torta-chocolate-1_04_13_2024-scaled.jpg', 'Tortas y Pasteles', 10, true),
('Cheesecake (Tarta de Queso)', 'Una tarta dulce con una base de galleta molida y un relleno cremoso hecho principalmente de queso crema, huevos y azúcar. Puede ir horneado o frío, y a menudo se cubre con salsa de frutas.', 23990, 'https://peopleenespanol.com/thmb/HkV2jbNhxgWQi7d0wSMFwEcMQ1w=/750x0/filters:no_upscale():max_bytes(150000):strip_icc()/cheesecake-facil-con-leche-condensada-2000-4160526441114bf3ad8f3409586a2c8a.jpg', 'Tortas y Pasteles', 10, true),
('Kuchen de Manzana (Tarta de Manzana)', 'Una tarta con base de masa y relleno de manzanas cocidas, a menudo condimentadas con canela. Puede tener una cubierta de masa (tipo "pie") o una cubierta de migas (streusel).', 18990, 'https://upload.wikimedia.org/wikipedia/commons/a/a6/Apple_cake_with_vanilla_ice_cream_2.jpg', 'Tortas y Pasteles', 10, true),
('Selva Negra', 'Una torta de capas de bizcocho de chocolate, remojado en kirsch (licor de cereza), con relleno de crema batida y cerezas. Se decora con más crema, virutas de chocolate y cerezas.', 26990, 'https://upload.wikimedia.org/wikipedia/commons/6/66/Black_Forest_gateau.jpg', 'Tortas y Pasteles', 10, true),
('Pie de Limón (Lemon Pie)', 'Una tarta con base de masa, relleno cremoso y ácido de limón (hecho con yemas de huevo y jugo de limón), y una cubierta de merengue dorado.', 17990, 'https://www.recetasnestle.cl/sites/default/files/styles/recipe_detail_desktop_new/public/srh_recipes/49d627e69672b6915c22f2eb2dfd1b93.webp?itok=cJEPzpNP', 'Tortas y Pasteles', 10, true),
('Torta Pastelera', 'Torta rellena de crema pastelera y cubierta con nueces frescas o glaseado.', 8990, 'https://i5.walmartimages.cl/asr/a1afe955-13cc-4f6b-94b2-8e608ad77570.0cbab0a9265430beeaf5a5598a443337.jpeg?null=&odnHeight=612&odnWidth=612&odnBg=FFFFFF', 'Tortas y Pasteles', 10, true);

-- Insertar Productos - Bollería y Masas Dulces
INSERT INTO PRODUCTO (nombre, descripcion, precio, imagen_url, categoria, stock, es_activo) VALUES
('Croissant (Medialuna)', 'Un panecillo de masa de hojaldre leudada, con una textura ligera, aireada y mantecosa. Ideal para el desayuno.', 1990, 'https://upload.wikimedia.org/wikipedia/commons/d/dc/Croissants_au_beurre_%2818953292873%29.jpg', 'Bollería y Masas Dulces', 20, true),
('Napolitana (o Caracola)', 'Una pieza de bollería hecha con masa de croissant, a menudo rellena de crema pastelera y pasas, o de chocolate.', 2290, 'https://upload.wikimedia.org/wikipedia/commons/5/5f/Pain_au_chocolat_Luc_Viatour.jpg', 'Bollería y Masas Dulces', 20, true),
('Donas (Rosquillas)', 'Una masa dulce frita, generalmente en forma de anillo o redonda y rellena. Pueden ir glaseadas, cubiertas de azúcar o rellenas de mermelada o crema.', 1590, 'https://upload.wikimedia.org/wikipedia/commons/e/ea/Chocolate_donuts_2.jpg', 'Bollería y Masas Dulces', 20, true),
('Roles de Canela (Cinnamon Rolls)', 'Un rollo de masa dulce (tipo brioche) relleno de una mezcla de canela y azúcar (a menudo con mantequilla) y cubierto con un glaseado de queso crema o azúcar.', 2990, 'https://i0.wp.com/sarasellos.com/wp-content/uploads/2024/05/cinnamon-rolls-rollos-canela-3.jpg?resize=1024%2C1024&ssl=1', 'Bollería y Masas Dulces', 20, true),
('Palmera', 'Una galleta o bollo de masa de hojaldre caramelizada, con una característica forma de corazón o palmera.', 1890, 'https://imag.bonviveur.com/palmeritas-de-hojaldre.webp', 'Bollería y Masas Dulces', 20, true),
('Muffin', 'Un pequeño panecillo dulce similar a un queque o magdalena, pero más denso. Popular en variedades como arándanos, chocolate o plátano.', 2190, 'https://www.vitamix.com/content/dam/vitamix/migration/media/recipe/rcppumpkinmuffins/images/pumpkinmuffinsmainjpg.jpg', 'Bollería y Masas Dulces', 20, true);

-- Insertar Productos - Panes Especiales
INSERT INTO PRODUCTO (nombre, descripcion, precio, imagen_url, categoria, stock, es_activo) VALUES
('Pan de Masa Madre (Sourdough)', 'Un pan hecho mediante una fermentación lenta usando un cultivo vivo de levaduras y lactobacilos (masa madre), lo que le da una corteza crujiente y una miga alveolada y ligeramente ácida.', 4490, 'https://upload.wikimedia.org/wikipedia/commons/3/3b/Home_made_sour_dough_bread.jpg', 'Panes Especiales', 15, true),
('Baguette', 'Una barra de pan larga y delgada, de origen francés, conocida por su corteza crujiente y su miga suave y aireada.', 1590, 'https://assets.tmecosys.com/image/upload/t_web_rdp_recipe_584x480/img/recipe/ras/Assets/f9f9282c-f4ab-480f-a42d-4347d51dfee2/Derivates/ae113aa0-b9c5-463c-b1e5-316f0390fb74.jpg', 'Panes Especiales', 15, true),
('Brioche', 'Un pan dulce de origen francés, enriquecido con una alta proporción de huevos y mantequilla, lo que le da una miga suave, tierna y de color amarillo.', 3990, 'https://www.harinaselecta.cl/img/blog/tabla-de-madera-con-pan-brioche-dulce-blog-selecta.webp', 'Panes Especiales', 15, true),
('Focaccia', 'Un pan plano italiano, horneado y a menudo cubierto con aceite de oliva, sal gruesa, y hierbas como el romero. Puede llevar también aceitunas o tomates cherry.', 3490, 'https://www.conasi.eu/blog/wp-content/uploads/2022/02/como-hacer-focaccia-desdes-900x563.jpg', 'Panes Especiales', 15, true);

-- Insertar Productos - Galletas y Pequeños Dulces
INSERT INTO PRODUCTO (nombre, descripcion, precio, imagen_url, categoria, stock, es_activo) VALUES
('Alfajores', 'Dos galletas suaves unidas por un relleno dulce, comúnmente dulce de leche, y a menudo cubiertas de chocolate o azúcar glas (azúcar impalpable).', 1990, 'https://upload.wikimedia.org/wikipedia/commons/a/ac/Alfajorartes.JPG', 'Galletas y Pequeños Dulces', 25, true),
('Galletas con Chispas de Chocolate', 'La clásica galleta mantecosa cargada de trozos o chispas de chocolate.', 1690, 'https://mojo.generalmills.com/api/public/content/_pLFRXFETcuXWg_Z0MhZPw_webp_base.webp?v=1c273e93&t=191ddcab8d1c415fa10fa00a14351227', 'Galletas y Pequeños Dulces', 25, true),
('Macarons', 'Un delicado dulce francés hecho a base de clara de huevo, almendra molida y azúcar. Son dos "conchas" crujientes por fuera y suaves por dentro, unidas por un relleno de ganache o crema.', 1890, 'https://upload.wikimedia.org/wikipedia/commons/4/49/Des_macarons_de_chez_Bouillet_%28mars_2023%29.jpg', 'Galletas y Pequeños Dulces', 25, true),
('Brownies', 'Un pequeño pastel de chocolate denso y compacto, a menudo con una textura "fudgy" (húmeda). Puede llevar nueces o chispas de chocolate.', 2490, 'https://icecreambakery.in/wp-content/uploads/2024/12/Brownie-Recipe-with-Cocoa-Powder.jpg', 'Galletas y Pequeños Dulces', 25, true),
('Merenguitos (Suspiros)', 'Pequeños dulces hechos de claras de huevo batidas con azúcar, horneados a baja temperatura hasta que quedan secos y crujientes.', 2990, 'https://www.recetasnestle.com.pe/sites/default/files/styles/recipe_detail_desktop_new/public/srh_recipes/f411ec369da32e4b42ed184220d30a85.webp?itok=xH9iySeF', 'Galletas y Pequeños Dulces', 25, true);
